apiVersion: v1
kind: Service
metadata:
  name: result-services
  labels:
    name: result-services
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    name: result-app-pod
    app: demo-voting-app